// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjhouhxasitabbqooqqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqaG91aHhhc2l0YWJicW9vcXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODIxNzcsImV4cCI6MjA2MDM1ODE3N30.GJ7CV3J7IdyY7_A4a0CsxWxBQ7nHpLnGD8bVlbKxJs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);